name: Validate tests against reference
on: 
    pull_request_target: 
        types: [opened, review_requested, ready_for_review, edited, synchronize]
    issue_comment:
        types: [created, deleted]
jobs:
  tests:
    name: Check that tests are valid
    if: github.repository_owner == 'browncs1260'
    runs-on: ubuntu-latest
    container:
        image: jiahuac/cs1260:main
        options: --user root  
    steps:
      - name: Check out assignments repo
        uses: actions/checkout@v4
        with:
            repository: 'BrownCS1260-fall-2023/finalhw-stencil'
            submodules: recursive
            path: 'hw'
      - name: Check out benchmark tests repo
        uses: actions/checkout@v4
        with:
            path: 'hw/benchmarks'
            ref: ${{ github.event.pull_request.head.sha }}
      - name: echo commit 
        run: echo "sha is ${{ github.event.pull_request.head.sha }}"
      - name: Run benchmarks
        working-directory: 'hw/benchmarks'
        run: chmod -R 1777 ../ && su - cs1260_user -c "cd $(pwd) && eval \$(opam env) && python3 bench.py --repeat 1"
    
